

sudo: required
dist: precise
language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-22
    - android-24
    - android-25
    - build-tools-25.0.2
    - extra-android-m2repository

env:
  matrix:
    - API=android-15 ABI=armeabi-v7a


script:
  - ./gradlew build
